# Generated by Django 4.0.6 on 2022-08-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webitbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='customer_dni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webitbank.cliente'),
        ),
    ]
