# Generated by Django 4.0.6 on 2022-08-22 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
