# Generated by Django 4.0.6 on 2022-08-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0002_movimientos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='cuenta_destinatario_id',
            new_name='cuenta_destinatario',
        ),
        migrations.RenameField(
            model_name='movimientos',
            old_name='cuenta_remitente_id',
            new_name='cuenta_remitente',
        ),
    ]
