# Generated by Django 4.0.6 on 2022-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocuenta',
            fields=[
                ('tipo_cuentaid', models.AutoField(db_column='tipo_cuentaId', primary_key=True, serialize=False)),
                ('tipo_cuenta', models.TextField()),
            ],
            options={
                'db_table': 'tipoCuenta',
                'managed': False,
            },
        ),
    ]
