# Generated by Django 4.0.6 on 2022-08-25 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webitbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Cliente ID')),
                ('customer_name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('customer_surname', models.CharField(max_length=40, verbose_name='Apellido')),
                ('customer_dni', models.IntegerField(verbose_name='DNI')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Dob')),
                ('tipo', models.CharField(choices=[('BLK', 'BLACK'), ('GLD', 'GOLD'), ('CLS', 'CLASSIC')], max_length=10, verbose_name='Tipo de cliente')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webitbank.sucursal', verbose_name='Sucursal ID')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webitbank.direcciones', verbose_name='Direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': True,
            },
        ),
    ]
