# Generated by Django 4.0.6 on 2022-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('tipo_clienteid', models.AutoField(db_column='tipo_clienteId', primary_key=True, serialize=False)),
                ('tipo_cliente', models.TextField()),
            ],
            options={
                'db_table': 'tipoCliente',
                'managed': False,
            },
        ),
    ]
