# Generated by Django 4.0.6 on 2022-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.TextField()),
                ('cvv', models.TextField()),
                ('fecha_otorgamiento', models.TextField()),
                ('fecha_expiracion', models.TextField()),
                ('marca_tarjetaid', models.TextField(db_column='marca_tarjetaId')),
                ('tipo_clienteid', models.TextField(db_column='tipo_clienteId')),
                ('tipo_cuentaid', models.TextField(db_column='tipo_cuentaId')),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
    ]
