# Generated by Django 4.0.6 on 2022-08-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('marca_tarjetaid', models.TextField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('tipo_clienteid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipocliente')),
                ('tipo_cuentaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.tipocuenta')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'cards',
                'managed': True,
            },
        ),
    ]
