# Generated by Django 4.0.6 on 2022-08-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='account_id',
            new_name='account',
        ),
    ]
