# Generated by Django 4.0.6 on 2022-08-23 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Prestamo')),
                ('loan_type', models.CharField(choices=[('HIP', 'HIPOTECARIO'), ('PER', 'PERSONAL'), ('PRE', 'PRENDARIO')], max_length=15, verbose_name='Tipo de prestamo')),
                ('loan_date', models.DateField(verbose_name='Fecha del prestamo')),
                ('loan_total', models.IntegerField(verbose_name='Monto')),
                ('estado', models.CharField(choices=[('PDT', 'PENDIENTE'), ('APB', 'APROBADO'), ('RZD', 'RECHAZADO')], max_length=15, verbose_name='Estado del prestamo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.cuenta', verbose_name='ID Cuenta')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'prestamo',
                'managed': True,
            },
        ),
    ]
